# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("控制面板")
        Form.resize(450, 700)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 450, 700))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setMinimumSize(100, 750)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 448, 698))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.posture_controller = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.posture_controller.setGeometry(QtCore.QRect(10, 10, 400, 350))
        self.posture_controller.setStyleSheet("background-color:rgb(0, 170, 0);")
        self.posture_controller.setObjectName("posture_controller")
        self.Slider_Rx = QtWidgets.QSlider(self.posture_controller)
        self.Slider_Rx.setGeometry(QtCore.QRect(150, 190, 160, 22))
        self.Slider_Rx.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Rx.setRange(-180, 180)
        self.Slider_Rx.setSingleStep(1)
        self.Slider_Rx.setObjectName("Slider_Rx")
        self.label_Rx = QtWidgets.QLabel(self.posture_controller)
        self.label_Rx.setGeometry(QtCore.QRect(41, 194, 85, 16))
        self.label_Rx.setObjectName("label_Rx")
        self.label_Y = QtWidgets.QLabel(self.posture_controller)
        self.label_Y.setGeometry(QtCore.QRect(41, 99, 85, 16))
        self.label_Y.setObjectName("label_Y")
        self.label_Z = QtWidgets.QLabel(self.posture_controller)
        self.label_Z.setGeometry(QtCore.QRect(41, 146, 85, 16))
        self.label_Z.setObjectName("label_Z")
        self.label_X = QtWidgets.QLabel(self.posture_controller)
        self.label_X.setGeometry(QtCore.QRect(41, 51, 85, 16))
        self.label_X.setObjectName("label_X")
        self.Slider_Y = QtWidgets.QSlider(self.posture_controller)
        self.Slider_Y.setGeometry(QtCore.QRect(150, 100, 160, 22))
        self.Slider_Y.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Y.setRange(-600, 600)
        self.Slider_Y.setSingleStep(1)
        self.Slider_Y.setObjectName("Slider_Y")
        self.Slider_X = QtWidgets.QSlider(self.posture_controller)
        self.Slider_X.setGeometry(QtCore.QRect(150, 50, 160, 22))
        self.Slider_X.setRange(-600, 600)
        self.Slider_X.setSingleStep(1)
        self.Slider_X.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_X.setObjectName("Slider_X")
        self.Slider_Z = QtWidgets.QSlider(self.posture_controller)
        self.Slider_Z.setGeometry(QtCore.QRect(150, 150, 160, 22))
        self.Slider_Z.setRange(-600, 600)
        self.Slider_Z.setSingleStep(1)
        self.Slider_Z.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Z.setObjectName("Slider_Z")
        self.label_Ry = QtWidgets.QLabel(self.posture_controller)
        self.label_Ry.setGeometry(QtCore.QRect(41, 241, 85, 16))
        self.label_Ry.setObjectName("label_Ry")
        self.Slider_Ry = QtWidgets.QSlider(self.posture_controller)
        self.Slider_Ry.setGeometry(QtCore.QRect(150, 240, 160, 22))
        self.Slider_Ry.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Ry.setRange(-180, 180)
        self.Slider_Ry.setSingleStep(1)
        self.Slider_Ry.setObjectName("Slider_Ry")
        self.label_Rz = QtWidgets.QLabel(self.posture_controller)
        self.label_Rz.setGeometry(QtCore.QRect(41, 289, 85, 16))
        self.label_Rz.setObjectName("label_Rz")
        self.Slider_Rz = QtWidgets.QSlider(self.posture_controller)
        self.Slider_Rz.setGeometry(QtCore.QRect(150, 290, 160, 22))
        self.Slider_Rz.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Rz.setRange(-180, 180)
        self.Slider_Rz.setSingleStep(1)
        self.Slider_Rz.setObjectName("Slider_Rz")
        self.joint_controller = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.joint_controller.setGeometry(QtCore.QRect(10, 370, 400, 350))
        self.joint_controller.setStyleSheet("background-color:rgb(0, 170, 0);")
        self.joint_controller.setObjectName("joint_controller")
        self.Slider_joint4 = QtWidgets.QSlider(self.joint_controller)
        self.Slider_joint4.setGeometry(QtCore.QRect(150, 190, 160, 22))
        self.Slider_joint4.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_joint4.setRange(-180, 180)
        self.Slider_joint4.setSingleStep(1)
        self.Slider_joint4.setObjectName("Slider_joint4")
        self.label_joint4 = QtWidgets.QLabel(self.joint_controller)
        self.label_joint4.setGeometry(QtCore.QRect(41, 194, 85, 16))
        self.label_joint4.setObjectName("label_joint4")
        self.label_joint2 = QtWidgets.QLabel(self.joint_controller)
        self.label_joint2.setGeometry(QtCore.QRect(41, 99, 85, 16))
        self.label_joint2.setObjectName("label_joint2")
        self.label_joint3 = QtWidgets.QLabel(self.joint_controller)
        self.label_joint3.setGeometry(QtCore.QRect(41, 146, 85, 16))
        self.label_joint3.setObjectName("label_joint3")
        self.label_joint1 = QtWidgets.QLabel(self.joint_controller)
        self.label_joint1.setGeometry(QtCore.QRect(41, 51, 85, 16))
        self.label_joint1.setObjectName("label_joint1")
        self.Slider_joint2 = QtWidgets.QSlider(self.joint_controller)
        self.Slider_joint2.setGeometry(QtCore.QRect(150, 100, 160, 22))
        self.Slider_joint2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_joint2.setRange(-180, 180)
        self.Slider_joint2.setSingleStep(1)
        self.Slider_joint2.setObjectName("Slider_joint2")
        self.Slider_joint1 = QtWidgets.QSlider(self.joint_controller)
        self.Slider_joint1.setGeometry(QtCore.QRect(150, 50, 160, 22))
        self.Slider_joint1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_joint1.setRange(-180, 180)
        self.Slider_joint1.setSingleStep(1)
        self.Slider_joint1.setObjectName("Slider_joint1")
        self.Slider_joint3 = QtWidgets.QSlider(self.joint_controller)
        self.Slider_joint3.setGeometry(QtCore.QRect(150, 150, 160, 22))
        self.Slider_joint3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_joint3.setObjectName("Slider_joint3")
        self.Slider_joint3.setRange(-180, 180)
        self.Slider_joint3.setSingleStep(1)
        self.label_joint5 = QtWidgets.QLabel(self.joint_controller)
        self.label_joint5.setGeometry(QtCore.QRect(41, 241, 85, 16))
        self.label_joint5.setObjectName("label_joint5")
        self.Slider_joint5 = QtWidgets.QSlider(self.joint_controller)
        self.Slider_joint5.setGeometry(QtCore.QRect(150, 240, 160, 22))
        self.Slider_joint5.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_joint5.setRange(-180, 180)
        self.Slider_joint5.setSingleStep(1)
        self.Slider_joint5.setObjectName("Slider_joint5")
        self.label_joint6 = QtWidgets.QLabel(self.joint_controller)
        self.label_joint6.setGeometry(QtCore.QRect(41, 289, 85, 16))
        self.label_joint6.setObjectName("label_joint6")
        self.Slider_joint6 = QtWidgets.QSlider(self.joint_controller)
        self.Slider_joint6.setGeometry(QtCore.QRect(150, 290, 160, 22))
        self.Slider_joint6.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_joint6.setRange(-180, 180)
        self.Slider_joint6.setSingleStep(1)
        self.Slider_joint6.setObjectName("Slider_joint6")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "控制面板"))
        self.posture_controller.setTitle(_translate("Form", "位姿控制"))
        self.label_Rx.setText(_translate("Form", "Rx：0"))
        self.label_Y.setText(_translate("Form", "Y：0"))
        self.label_Z.setText(_translate("Form", "Z：0"))
        self.label_X.setText(_translate("Form", "X：0"))
        self.label_Ry.setText(_translate("Form", "Ry：0"))
        self.label_Rz.setText(_translate("Form", "Rz：0"))
        self.joint_controller.setTitle(_translate("Form", "关节点控制"))
        self.label_joint4.setText(_translate("Form", "joint4：0"))
        self.label_joint2.setText(_translate("Form", "joint2：0"))
        self.label_joint3.setText(_translate("Form", "joint3：0"))
        self.label_joint1.setText(_translate("Form", "joint1：0"))
        self.label_joint5.setText(_translate("Form", "joint5：0"))
        self.label_joint6.setText(_translate("Form", "joint6：0"))
